# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339a3785525dfae6dff27b77620fa94cf5a8536670f1dbfbd1d9ec8c515371190074f1c300c1f46faa256e7796478670700380f12b81c2175cd8b355b9bd7aaa

test:
  secret_key_base: 435db40af9b2faaac1bbf5088e5abb2f4aea19386add33bad1362725bac6f50aeaea9365d856b80c3ba14fab8862fda2b940e236b6a84435fea05a212bcbee80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
